{
    'name': 'Pressence',
    'version': '1.0',
    'summary': 'Absensi Petugas OB',
    'description': 'Modul untuk mencatat dan melaporkan absensi petugas office boy.',
    'category': 'Human Resources',
    'author': 'Generated by ChatGPT',
    'depends': ['base'],
    'data': [
        'security/ir.model.access.csv',
        'views/pressence_item_views.xml',
        'views/pressence_menus.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
}
